[.text-justify]
= JImageHash - OSGi Bundle
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font
// Docinfo is used for foldable TOC.
// -> For full usage example see https://github.com/remkop/picocli
:docinfo: shared,private
:linkcss:
:stylesdir: https://www.ciechanowiec.eu/linux_mantra/
:stylesheet: adoc-css-style.css

== Overview

This repository delivers a shaded OSGi bundle of https://github.com/KilianB/JImageHash[_JImageHash_] for running inside the https://github.com/ciechanowiec/sling_rocket[_Sling Rocket_] environment.

. Maven coordinates for the bundle delivered by this repository:
+
[source, xml]
----
<dependency>
    <groupId>eu.ciechanowiec</groupId>
    <artifactId>jimage.hash</artifactId>
    <version>1.0.0</version>
</dependency>
----
. Maven coordinates for the original _JImageHash_:
+
[source, xml]
----
<dependency>
   <groupId>dev.brachtendorf</groupId>
   <artifactId>JImageHash</artifactId>
   <version>1.0.0</version>
</dependency>
----

. To run the bundle delivered by this repository, Java 21 or higher is required.

. All dependencies not present in the https://github.com/ciechanowiec/sling_rocket[_Sling Rocket_] environment and required by the bundle delivered by this repository are embedded within the bundle itself, ensuring it is self-sufficient and ready to run.

== License
The program is subject to MIT No Attribution License

Copyright © 2024 Herman Ciechanowiec

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.
